"""create apods table

Revision ID: db6c07430b1e
Revises: 
Create Date: 2026-05-18 20:20:28.320462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6c07430b1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('hdurl', sa.String(length=2000), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('copyright', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_apod_date')
    )
    op.create_index(op.f('ix_apods_date'), 'apods', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apods_date'), table_name='apods')
    op.drop_table('apods')
    # ### end Alembic commands ###
